using Base;
using UnityEngine;

namespace Test
{
    public class InitClock : MonoBehaviour
    {
        private static float timer = 0;

        // Start is called once before the first execution of Update after the MonoBehaviour is created
        private void Start()
        {
            var clock = Clock.Instance;
        }

        // Update is called once per frame
        //void Update()
        //{
        //    if (Input.GetKeyUp(KeyCode.W))
        //    {
        //        SceneManager.LoadScene("SampleScene");
        //    }
        //    if (timer > 1)
        //    {
        //        timer -= 1;
        //        Debug.Log("��������ʱ�ӳ�ʼ����");
        //    }
        //    timer += Time.deltaTime;
        //}
    }
}